name = 'void-rp'
host = '0.0.0.0'
port = 7788
players = 128
announce = false
language = 'en'
modules = ['js-module', 'js-bytecode-module']
resources = [
    'shared-variables',
    'auth',
    'chat',
    'freeroam',
    'phone',
    'systemctl',
    'reconnect',
    'call-app',
]

debug = true

duplicatePlayers = 5

[worldProfiler]
port = 7797
host = "0.0.0.0"

[maxStreaming]
peds = 128
objects = 120
vehicles = 128
entities = 128
